feac(stats): ajoute le sels aux statistiques de la métropole
MTES-MCT/camino pull request #207
Opened 2022-10-03 15:11 UTC by MichaelBitard

- chore(updates): CI + docs
- met à jour les sources
- chore(api): rend les statuts des phases statique
- PR review #1
- wip
- feat(stats): ajoute la production de sels

2022-10-03 15:11 UTC, MichaelBitard commented
![](https://github.trello.services/images/mini-trello-icon.png) [Cas France Relance : dashboard grand public, complète les statistiques V3 (SEL)](https://trello.com/c/d6YDa4Ao/341-cas-france-relance-dashboard-grand-public-compl%C3%A8te-les-statistiques-v3-sel)

2022-10-05 07:14 UTC, vmaubert requested changes

2022-10-05 07:14 UTC, vmaubert commented on packages/api/src/api/rest/statistiques.ts
> +        territoires: 'FR'
Territoires ça match aussi dans les communes, les départements et les régions. Donc on risque de se retrouvé avec des titres qui ne sont pas en métropole.
Test en prod => https://camino.beta.gouv.fr/titres?vueId=carte&territoires=FR&zoom=6&centre=46.227103425310766,2.499999999999991
1 titre n’est pas en métropole, mais d’un autre domaine. Donc ça marche, mais avec de la chance.

2022-10-05 07:21 UTC, MichaelBitard commented on packages/api/src/api/rest/statistiques.ts
> +        territoires: 'FR'
J'ai changé le comportement de ça justement, je voulais aller plus bourrin mais je voulais vous demander d'abord.

J'ai mis un nouveau comportement de power user ici : https://github.com/MTES-MCT/camino/blob/master/packages/api/src/database/queries/_titres-filters.ts#L223

J'aurais voulu mettre le reste dans un else, ça vous va ?

2022-10-05 07:33 UTC, vmaubert approved these changes

2022-10-05 07:35 UTC, merged