Stats guyane graphs
MTES-MCT/camino pull request #258
Opened 2022-11-16 10:59 UTC by bbbenja

2022-11-28 14:19 UTC, bbbenja commented
![](https://github.trello.services/images/mini-trello-icon.png) [feat(stats Guyane) : mise à jour et compléments](https://trello.com/c/FjagPit0/392-featstats-guyane-mise-%C3%A0-jour-et-compl%C3%A9ments)

2022-11-29 08:27 UTC, MichaelBitard approved these changes

2022-11-29 08:36 UTC, vmaubert requested changes

2022-11-29 08:36 UTC, vmaubert commented on packages/api/src/api/rest/statistiques/evolution-titres.ts
> +          where et.type_id = '${ETAPES_TYPES.depotDeLaDemande}'
and et.archive is false

2022-11-29 08:36 UTC, vmaubert commented on packages/api/src/api/rest/statistiques/evolution-titres.ts
> +           ((et.type_id in (${toJoinSQL(
and et.archive is false

2022-11-29 08:54 UTC, merged