feat(machine): ajout d'un delai de 30j entre la saisine des services …
MTES-MCT/camino pull request #321
Opened 2023-01-10 11:26 UTC by bbbenja

…et l'apd

2023-01-10 14:39 UTC, MichaelBitard approved these changes

2023-01-11 09:43 UTC, vmaubert commented on packages/api/src/business/rules-demarches/machine-helper.ts
> -      return { type: eventFromEntry }
@MichaelBitard Ok je comprends mieux de quoi tu parlais. 
Il y a beaucoup de délais à gérer dans Camino qu'on ne gère pas pour le moment, mais vu cette PR je pense qu'on va enfin les mettre. Donc j'aurai plutôt mis la `date` partout et donc gardé le code existant.

2023-01-11 09:46 UTC, vmaubert requested changes

2023-01-11 09:46 UTC, vmaubert commented on packages/common/src/date.ts
> +export function ajouteJour(date: CaminoDate, jours: number): CaminoDate {
`dateAddDays` a la même signature et le même comportement dans packages/api/src/tools/date.ts

2023-01-12 08:19 UTC, MichaelBitard commented on packages/api/src/business/rules-demarches/machine-helper.ts
> -      return { type: eventFromEntry }
Bof, du code qui ne sert à rien, ça se supprime :)
On le remettra à la prochaine machine non ?

2023-01-12 08:25 UTC, MichaelBitard requested changes

2023-01-12 08:25 UTC, MichaelBitard commented on packages/api/src/business/rules-demarches/axm/oct.machine.ts
> +      dateAddMonths(context.saisineDesServices.date, 1),
Je n'ai pas l'impression que c'est ce que veut Stéphanie, dans son mail elle a dit "au moins 30 jours" non ?

2023-01-12 08:25 UTC, MichaelBitard commented on packages/common/src/date.ts
> +// ajoute une durée en jours à une string au format YYYY-MM-DD
```suggestion
```

2023-01-12 08:25 UTC, MichaelBitard commented on packages/common/src/date.ts
> +// ajoute une durée en mois à une string au format YYYY-MM-DD
```suggestion
```

2023-01-12 08:25 UTC, MichaelBitard commented on packages/common/src/date.ts
> +export const datesSubtract = (dateDebut: string, dateFin: string) => {
Supprimer le commentaire et renommer la function ? Utiliser des CaminoDate plutôt que des string

2023-01-12 08:25 UTC, MichaelBitard commented on packages/common/src/date.ts
> +export function moveToDayInMonth(date: CaminoDate, day: number): CaminoDate {
Je suis pas sûr de comprendre son utilité :)

2023-01-12 08:36 UTC, vmaubert commented on packages/api/src/business/rules-demarches/machine-helper.ts
> -      return { type: eventFromEntry }
Justement j’ai l’impression que vous avez ajouté du code :-) Mais ok.

2023-01-12 08:38 UTC, MichaelBitard commented on packages/api/src/business/rules-demarches/machine-helper.ts
> -      return { type: eventFromEntry }
Ha pardon, je vois ce que tu veux dire. Que date soit dans tous les contextes tout le temps c'est ça ?

2023-01-12 10:33 UTC, MichaelBitard commented on packages/api/src/business/rules-demarches/machine-helper.ts
> -      return { type: eventFromEntry }
Après avoir fouillé, ça demande un peu de travail, pour éviter que tous les events aient date alors qu'elles n'en ont pas besoin.

Pour le moment on garde comme ça on verra avec les pex geothermie

2023-01-12 10:34 UTC, MichaelBitard commented on packages/api/src/business/rules-demarches/axm/oct.machine.ts
> +      dateAddMonths(context.saisineDesServices.date, 1),
Je lui ai demandé directement, mais ça a l'air d'être la bonne règle

2023-01-12 16:01 UTC, merged