style(footer): applique le design de l'état au pied de page
MTES-MCT/camino pull request #326
Opened 2023-01-11 08:29 UTC by vmaubert

2023-01-11 14:03 UTC, bbbenja requested changes

2023-01-11 14:03 UTC, bbbenja commented on packages/ui/package.json
> +    "@gouvfr/dsfr": "^1.8.5",
comme discuté ensemble, c'est sûrement pas utile de l'avoir dans le `package.json` et ça peut être installé via le `Makefile` avant l'import

2023-01-12 10:14 UTC, MichaelBitard commented on packages/ui/src/app.vue
> -    <footer class="footer">
T'as supprimer la classe footer dans notre css ?

2023-01-12 10:14 UTC, MichaelBitard commented on packages/ui/src/components/page/footer/newsletter-form.vue
> -          S'inscrire
est-ce qu'il y'a du nettoyage possible sur les classes ici qui seraient utilisées qu'ici ?

2023-01-12 10:14 UTC, MichaelBitard commented on packages/ui/src/components/page/pure-footer.stories.tsx
> +    displayNewsletter={true}
```suggestion
    displayNewsletter={false}
```

2023-01-12 10:14 UTC, MichaelBitard commented on packages/ui/src/components/page/pure-footer.vue
> -                class="sponsor"
class jamais plus utilisée ?

2023-01-17 09:22 UTC, vmaubert commented on packages/ui/src/app.vue
> -    <footer class="footer">
Oui

2023-01-17 09:30 UTC, vmaubert commented on packages/ui/src/components/page/footer/newsletter-form.vue
> -          S'inscrire
J’ai supprimé `blob-mini-2-3`

2023-01-18 10:03 UTC, merged