refactor(role): supprime les permissions de la bdd et les remplace par un role du code
MTES-MCT/camino pull request #88
Opened 2022-06-13 15:20 UTC by vmaubert

2022-06-14 13:41 UTC, vmaubert commented on packages/api/src/database/queries/permissions/titres.ts
> +  if (!user || !(isSuper(user) || isAdministrationEditeur(user))) {
```suggestion
  if (!user || !(isSuper(user) || isAdministrationAdmin(user) || isAdministrationEditeur(user) || isAdministrationLecteur(user))) {
```

2022-06-14 13:41 UTC, vmaubert commented on packages/api/src/api/graphql/resolvers/titre-demande.ts
> +      isSuper(
gni

2022-06-14 13:41 UTC, MichaelBitard requested changes

2022-06-14 13:41 UTC, MichaelBitard commented on packages/api/src/database/queries/permissions/metas.ts
> +  if (!user || isDefault(user) || isEntreprise(user)) {
```suggestion
  if (isDefault(user) || isEntreprise(user)) {
```

2022-06-14 13:41 UTC, MichaelBitard commented on packages/api/src/database/queries/permissions/metas.ts
> -
Useless?

2022-06-14 13:41 UTC, MichaelBitard commented on packages/api/src/database/queries/permissions/titres-demarches.ts
> +  if (!user || !isSuper(user)) {
```suggestion
  if (!isSuper(user)) {
```

2022-06-14 13:41 UTC, MichaelBitard commented on packages/api/src/database/queries/permissions/titres-etapes.ts
> +  if (!user || !isSuper(user)) {
```suggestion
  if (!isSuper(user)) {
```

2022-06-14 13:41 UTC, MichaelBitard commented on packages/api/src/database/queries/permissions/titres.ts
> +  if (!user || !isSuper(user)) {
```suggestion
  if (!isSuper(user)) {
```

2022-06-14 13:41 UTC, MichaelBitard commented on packages/api/src/database/queries/permissions/titres.ts
> +  if (!user || !(isSuper(user) || isAdministrationEditeur(user))) {
```suggestion
  if (!(isSuper(user) || isAdministrationEditeur(user)) {
```

2022-06-14 13:41 UTC, MichaelBitard commented on packages/api/src/database/queries/permissions/utilisateurs.ts
> +  } else if (user && isDefault(user)) {
```suggestion
  } else if (isDefault(user)) {
```

2022-06-14 13:41 UTC, MichaelBitard commented on packages/common/src/roles.test.ts
> +  expect(isSuper({ role: 'entreprise' })).toBe(false)
```suggestion
  expect(isSuper({ role: 'entreprise' })).toBe(false)
  expect(isSuper(undefined)).toBe(false)
```

2022-06-14 13:41 UTC, MichaelBitard commented on packages/common/src/roles.test.ts
> +  expect(isAdministration({ role: 'super' })).toBe(false)
```suggestion
  expect(isAdministration({ role: 'super' })).toBe(false)
  expect(isAdministration(undefined)).toBe(false)
```

2022-06-14 13:41 UTC, MichaelBitard commented on packages/ui/src/components/utilisateur/password-popup.vue
> +    <div v-if="needOldPassword(user)">
why not just `isSuper`?

2022-06-14 13:41 UTC, MichaelBitard commented on packages/ui/src/store/user.test.js
> +  `('ajoute des jours à une date', ({ role, isAdmin }) => {
```suggestion
  `('ajoute un utilisateur au store avec le role $role et vérifie si il est admin $isAdmin', ({ role, isAdmin }) => {
```

2022-06-14 13:41 UTC, MichaelBitard commented on packages/ui/src/store/utilisateurs.test.js
> +      { id: 'roles', type: 'strings', values: [] },
that's strange right?

2022-06-15 08:38 UTC, MichaelBitard approved these changes

2022-06-15 09:02 UTC, merged