feat(keycloak): ajoute un serveur d’authentification
MTES-MCT/camino pull request #98
Opened 2022-06-23 12:11 UTC by vmaubert

## Checklist

* [ ] Faire plein d'actions sur la preprod (créer des titres, télécharger des fichiers, remplir des activités, supprimer des utilisateurs, ....)
* [ ] Se déconnecte/reconnecter
* [ ] Créer un compte
* [ ] Se connecter avec Cerbère
* [ ] Changer son mot de passe
* [ ] Changer le role d'un utilisateur
* [ ] ...

2022-10-20 07:48 UTC, vmaubert commented
![](https://github.trello.services/images/mini-trello-icon.png) [chore(sécu): mettre keycloak en place](https://trello.com/c/9T34Z8lx/174-chores%C3%A9cu-mettre-keycloak-en-place)

2023-02-15 15:48 UTC, MichaelBitard requested changes

2023-02-15 15:48 UTC, MichaelBitard commented on packages/ui/src/api/_client.js
> +    // if (e.status === 401 || e.message === 'HTTP 401 status.') {
à remettre avant le merge

2023-02-16 15:38 UTC, MichaelBitard approved these changes

2023-02-16 15:43 UTC, merged